# Generated by Django 5.2.8 on 2025-11-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="credential",
            name="issued_at",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="subject_did",
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="credential",
            name="hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="credential",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="credentials.issuer",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="credentials.subject",
            ),
        ),
    ]
