# Generated by Django 5.2.8 on 2025-12-17 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_subject_remove_credential_issued_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credential",
            name="credential_type",
        ),
        migrations.RemoveField(
            model_name="issuer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="email",
        ),
        migrations.AddField(
            model_name="credential",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="type",
            field=models.CharField(default="credential", max_length=100),
        ),
        migrations.AlterField(
            model_name="credential",
            name="hash",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="credential",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials",
                to="credentials.issuer",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials",
                to="credentials.subject",
            ),
            preserve_default=False,
        ),
    ]
